name: Deploy Website to Fornex via SFTP

on:
  push:
    branches:
      - eye-clinic-site

concurrency:
  group: production-deploy
  cancel-in-progress: true

jobs:
  web-deploy:
    name: 🚀 Deploy WordPress to Fornex
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout repository
        uses: actions/checkout@v4

      - name: 📂 Sync files via SFTP (rsync)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }} # Твій IP: 176.10.124.188 або hostch01.fornex.org
          username: ${{ secrets.FTP_USERNAME }} # a49718
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: sftp
          port: 22 # або 1022 якщо стандартний закритий
          server-dir: ./public_html/med.uz.ua/
          exclude: |
            **/.git*
            **/.github/**
            **/.idea/**
            **/.junie/**
            **/node_modules/**
            **/.DS_Store
            **/.well-known/**
            error_log
            wp-config.php
            wp-content/uploads/**
            wp-content/cache/**